/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpb.dac.jpa.oficina.jse.app;

/**
 *
 * @author Pedro Arthur
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnNewEmployee = new javax.swing.JMenuItem();
        btnSearchEmployee = new javax.swing.JMenuItem();
        btnLocateEmployee = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnNewFactory = new javax.swing.JMenuItem();
        btnListFactories = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnNewRepair = new javax.swing.JMenuItem();
        btnListRepairs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Funcionários");

        btnNewEmployee.setText("Novo Funcionário");
        btnNewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewEmployeeActionPerformed(evt);
            }
        });
        jMenu1.add(btnNewEmployee);

        btnSearchEmployee.setText("Buscar Funcionário");
        btnSearchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEmployeeActionPerformed(evt);
            }
        });
        jMenu1.add(btnSearchEmployee);

        btnLocateEmployee.setText("Alocar Funcionário");
        btnLocateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocateEmployeeActionPerformed(evt);
            }
        });
        jMenu1.add(btnLocateEmployee);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Oficinas");

        btnNewFactory.setText("Nova Oficina");
        btnNewFactory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewFactoryActionPerformed(evt);
            }
        });
        jMenu2.add(btnNewFactory);

        btnListFactories.setText("Listar Oficinas");
        jMenu2.add(btnListFactories);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consertos");

        btnNewRepair.setText("Novo Conserto");
        jMenu3.add(btnNewRepair);

        btnListRepairs.setText("Listar Consertos");
        jMenu3.add(btnListRepairs);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEmployeeActionPerformed
        EmployeeFrame frame = new EmployeeFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_btnSearchEmployeeActionPerformed

    private void btnNewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewEmployeeActionPerformed
        NewEmployeeFrame frame = new NewEmployeeFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_btnNewEmployeeActionPerformed

    private void btnNewFactoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewFactoryActionPerformed
        NewFactoryFrame frame = new NewFactoryFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_btnNewFactoryActionPerformed

    private void btnLocateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocateEmployeeActionPerformed
        LocateEmployeeFrame frame = new LocateEmployeeFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_btnLocateEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnListFactories;
    private javax.swing.JMenuItem btnListRepairs;
    private javax.swing.JMenuItem btnLocateEmployee;
    private javax.swing.JMenuItem btnNewEmployee;
    private javax.swing.JMenuItem btnNewFactory;
    private javax.swing.JMenuItem btnNewRepair;
    private javax.swing.JMenuItem btnSearchEmployee;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
